# Note the nsq version and the go version MUST match
# the releases found at https://github.com/bitly/nsq/releases
nsq_version: 0.3.5
nsq_go_version: 1.4.2

nsq_dir: /usr/bin
nsq_lookupd_log_file: /var/log/nsqlookupd.log
nsq_lookupd_pid_file: /var/run/nsqlookupd.pid

nsq_lookupd_tcp_port: 4160
nsq_lookupd_http_port: 4161